### ISSUE TITLE
possible bug in PRTE

### ISSUE THREAD

**Issue by angainor** [pmix/prrte#106] opened 2018-10-23 11:09 UTC
Playing a bit with PRRTE I ran into what I suspect might be a bug in `prte`. I compiled `master` with external PMIx 3.0.2. I then ran the simple test on my laptop: I started `prte -d` in one terminal, and used `prun` to run a client:

```
prun -np 1 pmix-3.0.2/examples/client
Client ns 2573926402 rank 0: Running
Client 2573926402:0 universe size 4
Client 2573926402:0 num procs 1
Client ns 2573926402 rank 0: Finalizing
Client ns 2573926402 rank 0:PMIx_Finalize successfully completed
```

So far so good. But then I `Ctrl-C` the client and didn't let it finish cleanly. After that, when I tried to `prun` angain, nothing happened. That is, `prun` doesn't show any output. I still do get debug messages on the `prte` console, so there is some activity going on between `prun` and `prte`, but the `client` is not executed. 

I've noticed that instead of aborting the client with a signal I can break `prte` in the same way by running the `alloc` example:

```
$ ~/work/pmi/install-prrte/bin/prun -np 1 ./alloc
Client ns 2554920962 rank 0: Running
Client 2554920962:0 universe size 4
Allocation request returned PROC-ABORT-REQUESTED
```

After that `prun` doesn't do anything anymore. So it seems that some behavior in the client can put the server into an unusable state.

**Comment by rhc54** [comment] 2018-10-23 16:06
Yes, that is expected - PRRTE is an offshoot of ORTE (the OMPI runtime) which was designed as a "single-shot" environment. We have slowly been going thru and cleaning up the places where it sets state such that all subsequent executions are rejected, but obviously haven't gotten them all yet.

I'll leave this open as a reminder to continue the cleanup.

**Comment by angainor** [comment] 2018-11-30 13:49
@rhc54 Since you have now released an RC of PRRTE, I'm wondering if you would like to get reports of similar problems. I was often running into cases, where I could only submit a job once, and after that `prte` would not start any more jobs.

**Comment by rhc54** [comment] 2018-11-30 15:28
Absolutely! If you can provide details of the sequence of commands that generated the situation, that would be very helpful indeed.

**Comment by rhc54** [comment] 2019-01-02 17:41
I believe this has been fixed via a combination of the recent changes to PRRTE plus PMIx. Once https://github.com/pmix/pmix/pull/1018 gets committed, I'd suggest giving the head of PRRTE + head of PMIx another shot. I've been running some fairly extensive uses of PRRTE (using an OSHMEM test suite) and everything seems to be running very well.

**Comment by rhc54** [comment] 2019-02-20 15:40
Please let us know if this persists.

**Closed by rhc54** 2019-02-20 15:40 UTC
