### ISSUE TITLE
stdin and PRRTE?

### ISSUE THREAD

**Issue by tonycurtis** [pmix/prrte#170] opened 2018-12-19 16:22 UTC
Thank you for taking the time to submit an issue!

### What version of the PMIx Reference Server are you using? (e.g., v1.0, v2.1, git master @ hash, etc.)

git master @ 4c77d72ea5167971080d40ee987e12ff315fe8dd

##### What version of PMIx are you using? (e.g., v1.2.5, v2.0.3, v2.1.0, git branch name and hash, etc.)

git master @ c82c6dca63036d06e75da3aff8df16165635a56c

### Please describe the system on which you are running

* Operating system/version: CentOS 7
* Computer hardware: x86_64
* Network type: IB

-----------------------------

## Details of the problem

Testing OpenSHMEM program that reads a value from stdin on start-up (rank 0 only). 

With OpenMPI 3.1.3 acting as launcher/server with PMIx 2.1.1 all is well.

With PRRTE/PMIx git combination, I get the prompt, enter a value, but then no progress.  Also takes significantly longer for the prompt to appear.

Simple test program:
```C
#include <stdio.h>
#include <shmem.h>

int
main()
{
    int n = -1;
    int me;

    shmem_init();
    me = shmem_my_pe();

    if (me == 0) {
        printf("Enter n : "); fflush(stdout);
        fscanf(stdin, "%d", &n);
        printf("You entered %d\n", n);
    }

    shmem_barrier_all();

    printf("PE %d: n = %d\n", me, n);

    return 0;
}
```

Expected result:
```shell
$ oshrun -n 2 ./a.out
oshrun:prrte: found "prun"
oshrun:prrte: check matching "prte"
oshrun:prrte: no "prte", skipping
oshrun:prrte: check matching "psrvr"
oshrun:prrte: no "psrvr", skipping
oshrun:launch: look for "mpiexec"
oshrun:launch: using "/gpfs/projects/ChapmanGroup/opt/openmpi/3.1.3/bin/mpiexec"
oshrun:launch: "mpiexec -n 2 ./a.out"
oshrun:----------------------------------------------------------------------
Enter n : 23
You entered 23
PE 0: n = 23
PE 1: n = -1
oshrun:launch: done
```

Bad result:
```shell
$ oshrun -n 2 ./a.out
oshrun:prrte: found "prun"
oshrun:prrte: check matching "prte"
oshrun:prrte: found "prte"
oshrun:prrte: starting up
oshrun:prrte: pid 31639 says "DVM ready"
oshrun:launch: "prun -n 2 ./a.out"
oshrun:launch: application in process 31741
oshrun:----------------------------------------------------------------------
Enter n : 23
<nothing more, hang>
```

**Comment by rhc54** [comment] 2018-12-19 16:40
Just to be clear: is this a regression? Or are you trying something new? I ask because the primary difference would seem to be the reading of stdin by orterun vs prun (and I doubt the latter has been tested before)

**Comment by tonycurtis** [comment] 2018-12-19 16:50
I think this is a new issue moving from launcher=OpenMPI to launcher=PRRTE, haven't tried interactive input example for a long time.

**Comment by rhc54** [comment] 2018-12-19 16:56
Okay, let me play with it a bit. Have to complete a problem first, but hopefully in the next day or two.

**Comment by tonycurtis** [comment] 2019-02-06 18:12
@rhc54 , any update on this?

**Comment by ggouaillardet** [comment] 2019-02-07 02:36
@tonycurtis which PMIx version are you using ?

we will shortly bump the prrte requirement since PMIx v2 does not do IOF forwarding.

**Comment by tonycurtis** [comment] 2019-02-07 02:37
Both pmix and prrte @ github master HEAD

**Comment by ggouaillardet** [comment] 2019-02-07 03:00
@tonycurtis thanks

@rhc54 the `PMIX_IOF_PUSH_STDIN` key is defined but it looks like the code to handle it is missing in both `prrte` and `pmix`

**Comment by rhc54** [comment] 2019-02-07 03:26
Correct - I just haven't had time to implement it yet. At the top of the "to-do" list, I fear.

**Comment by rhc54** [comment] 2019-02-07 03:43
@ggouaillardet I'll make you a deal you cannot refuse 😄  I'll get this implemented if you can fix https://github.com/open-mpi/ompi/pull/6350. PMIx is complaining because the number of nodes isn't matching the number of ppn entries being passed to it. The code generating the info is in orte/orted/pmix/pmix_server_register_fns.c, but the root-cause lies in orte/util/nidmap.c.

I can add more explanation over there - fair trade?

**Comment by ggouaillardet** [comment] 2019-02-07 04:03
deal !

let me see if I can easily reproduce the issue first.
(btw, what kind of VM are you using ?)

**Comment by rhc54** [comment] 2019-02-07 04:09
It's a VirtualBox running Ubuntu - not sure why it is grinding to a halt and haven't had time to investigate.

**Comment by rhc54** [comment] 2019-02-20 01:40
@tonycurtis My deepest apologies for how late this has become. Afraid I've been stomping on fires for quite some time. You will find the fix consists of PR's to both sides: https://github.com/pmix/pmix/pull/1124 and https://github.com/pmix/prrte/pull/206 (which cannot pass until the PMIx side is committed).

I have only lightly tested this and so I make no promises that it will handle arbitrary scenarios. However, my "simpio" tester in the PMIx test/simple directory seems to work, so I have some hope of success. Please let me know what you see!

**Comment by tonycurtis** [comment] 2019-02-20 14:53
@rhc54 no rush on this.  I've just it-pulled and rebuilt.  Looks to be working!

thanks

**Comment by rhc54** [comment] 2019-02-20 15:38
Great! I'll close this for now.

**Closed by rhc54** 2019-02-20 15:38 UTC
